name: Release

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/**"
      - "**.md"
      - "docs/**"

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
          MAJOR_STRING_TOKEN: "BREAKING CHANGE"
          MINOR_STRING_TOKEN: "feat:"
          PATCH_STRING_TOKEN: "fix:"
